### ISSUE TITLE
Initialize cluster via connection URL

### ISSUE THREAD

**Issue by selevit** [zifter/clickhouse-migrations#24]
Hi, and thanks for the great library!

Wanted to mention that it would be nice to be able to initialize the `ClickhouseCluster` class via a URL like `clickhouse//:user:password@host...`. The `clickhouse_driver` library that you use actually supports it via a [Client.from_url](https://clickhouse-driver.readthedocs.io/en/latest/api.html#clickhouse_driver.Client.from_url) static method. 

Unfortunately, `clickhouse_driver` does not yet expose the "parse url" API, and I need to parse the URL manually to pass it to `ClickhouseCluster`.

**Comment by zifter** [comment]
Hey,

Thank you for the idea.

I made the requested changes, https://github.com/zifter/clickhouse-migrations/pull/25

You can find the necessary changes in the latest release 0.7.0

**Comment by selevit** [comment]
Hello, thanks a lot for implementing this!

There is a minor issue that I wanted to report. Now it's possible to pass a default database for migration into `ClickhouseCluster` (via a URL), but `ClickhouseCluster.migrate` requires `db_name` to be passed. Would be nice to make this parameter optional.

Because `clickhouse_driver` does not yet expose their URL parsing API (I also created a [ticket](https://github.com/mymarilyn/clickhouse-driver/issues/438) in their issues).

It means that to supply `db_name` to `ClickhouseCluster` I need to parse the URL myself, i.e. reimplement this logic of `Client.from_url`. It doesn't make a lot of sense, since `clickhouse-migrations` supports the db URL now.

**Comment by zifter** [comment]
#26 is merged
@selevit can you check the latest release 0.7.1?

**Comment by selevit** [comment]
Big thanks for the quick fix!

It worked for me. Just a minor – IMO it looks a bit weird that it's required to pass the db name explicitly as None, like this.

```python
cluster.migrate(
    db_name=None,  # use default db
    migration_path=MIGRATIONS_DIR,
    ...
)
```

**Comment by zifter** [comment]
@selevit yes, looks weird, but I don't want to make breaking changes in API
