### ISSUE TITLE
Is there a hope to get rid of heavyweight pandas ?

### ISSUE THREAD

**Issue by remort** [zifter/clickhouse-migrations#9]
Pandas is heavy to pull it to a tiny microservice container every time we just need to run migrations before the start of this microservice.
I see you use it in migrator.py to merge lists of migrations by certain criterion. May it be rewritten in pure python or by the means of lighter libs, please? ;)

**Comment by zifter** [comment]
Hi, @remort!
It's good idea! Is it ok to you make changes to get rid of pandas?

**Comment by zifter** [comment]
@remort 
https://pypi.org/project/clickhouse-migrations/0.3.0/
happy to use)

**Comment by remort** [comment]
Thank you very much, @zifter. Have just rebuilt my container with the version 0.3.0 - no pandas and numpy anymore. Thank you for keeping this handy tool up.
